site_name: Waiwera
theme:
  name: 'material'
  logo: 'img/waiwera_logo_square.png'
  favicon: 'img/waiwera.ico'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/waiwera/waiwera'

nav:
  - 'Introduction': 'index.md'
  - 'News': 'news.md'
  - 'User guide': 'userguide.md'
  - 'Installation': 'install.md'
  - 'License': 'license.md'
  - 'Issues': 'issues.md'
  - 'Contributing': 'contrib.md'
  - 'Publications': 'pubs.md'

site_description: "Waiwera parallel open-source geothermal flow simulator"

repo_url: https://github.com/waiwera/waiwera
edit_uri: ""

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
